"""hybrid user model

Revision ID: b0491b975415
Revises: eb36075b0bc0
Create Date: 2025-12-10 09:24:51.807866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0491b975415'
down_revision: Union[str, Sequence[str], None] = 'eb36075b0bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
