"""initial schema

Revision ID: eb36075b0bc0
Revises: 
Create Date: 2025-12-09 13:44:38.316684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb36075b0bc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('apex_user_id', sa.String(
                        length=100), nullable=True),
                    sa.Column('email', postgresql.CITEXT(), nullable=False),
                    sa.Column('full_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('role', sa.String(length=50),
                              server_default='user', nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_apex_user_id'),
                    'users', ['apex_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversations',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversations_user_id'),
                    'conversations', ['user_id'], unique=False)
    op.create_table('sessions',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('refresh_token', sa.String(), nullable=False),
                    sa.Column('user_agent', sa.String(), nullable=True),
                    sa.Column('ip_address', sa.String(), nullable=True),
                    sa.Column('expires_at', sa.TIMESTAMP(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('refresh_token')
                    )
    op.create_table('messages',
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('role', sa.String(length=20), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('mode', sa.String(length=20), nullable=True),
                    sa.Column('label', sa.String(length=50), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                        'conversations.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_conversation_id'),
                    'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_apex_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
